name: ▶️ Deploy to GitHub Pages & Wix

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy frontend/dist to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist

  build-and-publish-to-wix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint & Test
        run: |
          npm run lint || true
          npm test || true

      - name: Install Wix CLI
        run: npm install -g @wix/cli@latest

      - name: Wix Login
        run: wix login --apiSecret ${{ secrets.WIX_API_SECRET }}

      - name: Publish to Wix
        run: wix publish
